### PR TITLE
schemathesis tests

### PR DESCRIPTION
**Pull request by A-Harby**
### Description

Creating a python file to run schemathesis api testing tool to generate and test all the endpoint, And adding workflow to run daily and create a test detailed report. 

### Related Issues

https://github.com/threefoldtech/tfgrid-sdk-go/issues/51

### CODE REVIEW

**Comment by A-Harby** [comment]
As per requested @sameh-farouk, added environment network variable to the workflow.

It can be changed from actions by manually trigger. 
image

**Comment by sameh-farouk** [comment]
@A-Harby  Can we add an option for a local instance as well, so, as we agreed, it would be possible to run later against a test instance in the pipeline before merging or deploying a new code?

**Comment by A-Harby** [comment]
Adding options to run on local instance, And limiting manual run to only local and dev.
image

**Comment by xmonader** [comment]
can we update and merge this PR?

**Comment by A-Harby** [comment]
It's updated, Just waiting for the reviews

**Pull request closed without merging**
