### PR TITLE
return an error if /gateways/<id> not a gateway

### PR DESCRIPTION
**Pull request by Omarabdul3ziz**
### Description
return error "node not a gateway"

### Changes

edits in `internal/explorer/server.go` `getGateway` function.

### Related Issues

- https://github.com/threefoldtech/tfgridclient_proxy/issues/225

### Checklist

- [x] Tests pass
- [x] Build pass
- [x] Code format and docstrings

### CODE REVIEW

**Review by sameh-farouk — COMMENTED** [review]
I have a question, as a gateway is just a node with specific properties, why do we define a new resource for it instead of adding a boolean flag/query `is_gateway` for the node's endpoints?

**Review by sameh-farouk — CHANGES_REQUESTED** [review]
regarding the code, my understanding is that it returns a 500 response status code error (correct me if I'm wrong), which is not a proper response code for such a case. should be 4xx, not found 404 IMO (as there is no gateway with such id).

**Comment by Omarabdul3ziz** [comment]
first comment: I don't know why it is implemented this way. if @AhmedHanafy725 have any inputs?
second comment: yes, it makes more sense. added a new error with status code `404` and error msg `gateway not found`

**Comment by AhmedHanafy725** [comment]
> first comment: I don't know why it is implemented this way. if @AhmedHanafy725 have any inputs?

it was done to get the gateways in an easy way and more like the grid2 for the aggregation in the unified explorer.
we can remove it and add just a query on the nodes as @sameh-farouk suggested but that is in a new APIs version threefoldtech/tfgrid-sdk-go#50

**Review by sameh-farouk — APPROVED** [review]

**Comment by Omarabdul3ziz** [comment]
created a new issue for that 
- https://github.com/threefoldtech/tfgridclient_proxy/issues/260

**Pull request merged**
